### ISSUE TITLE
Bug in useArray

### ISSUE THREAD

**Issue by 3noix** [WebDevSimplified/useful-custom-react-hooks#11]
In the "update" and "remove" functions, it should be "a.length" instead of "a.length-1", as with the "slice" function, the second index is not included in the result. The problem can even be seen in the result of the demo in the youtube video (after 9m55 in https://www.youtube.com/watch?v=0c6znExIqRw)

**Comment by WebDevSimplified** [comment]
Good catch. This will be fixed in the next update I make to the library. I have 5 hooks I am planning to add in a week or so.
