### ISSUE TITLE
Turn this repo into an npm package

### ISSUE THREAD

**Issue by niemenjoki** [WebDevSimplified/useful-custom-react-hooks#14]
I think these hooks could be useful as a simple npm package people could use easily in their projects. What do you think @WebDevSimplified? Just close this issue if you don't think it's a good idea, I don't mind.

The example components you've made for each hook could easily be used as test components for unit tests, and then all we need is some simple documentation. I would be glad to contribute.

**Comment by WebDevSimplified** [comment]
Most of these hooks are either already in larger hook based libraries or too small to warrant their own library. My main idea with this repo is to give people ideas where they can pick and choose which hooks fit their needs best instead of just using all the hooks in a library.
