### ISSUE TITLE
Please add hacktoberfest tags in repo 

### ISSUE THREAD

**Issue by TheSwordBreaker** [WebDevSimplified/useful-custom-react-hooks#15]
#supportNewbies

**Comment by SaharshSamir** [comment]
Hey can u assign me this issue?

**Comment by WebDevSimplified** [comment]
I do not plan to accept any changes to this repo as it is directly linked to the video series on my YouTube channel about these hooks. Each hook in this repo is part of one of those videos and any new hooks will also be a part of one of my videos.
