### ISSUE TITLE
Make useful-custom-react-hooks a npm package

### ISSUE THREAD

**Issue by Async10** [WebDevSimplified/useful-custom-react-hooks#22]
Hi Kyle. First of all thank you for this collection of awesome utitly hooks. You mentioned that you would be open to add TypeScript versions of your hooks in a seperate branch. I would love that and I would like to actually  go one step further. How about making this TS branch a npm package and publish it so people can easily use these hooks in their projects. With you permission i would like to work on that.

**Comment by WebDevSimplified** [comment]
If you want to work on making TS versions and publishing your own package of these you are more than welcome to. I do not have any intent to personally create TS versions of these or publish a package for the code as I do not have the time to, but you can.

**Comment by Async10** [comment]
Ok, that is understandable. Then I'll start working on the package on my own.
