### ISSUE TITLE
useStateWithHistory return problems

### ISSUE THREAD

**Issue by jkutianski** [WebDevSimplified/useful-custom-react-hooks#3]
https://github.com/WebDevSimplified/useful-custom-react-hooks/blob/f5dda2e69d51e5da52aa75f21c6e83610def5923/src/7-useStateWithHistory/useStateWithHistory.js#L51

Similar to #2 
Especially painful if you already use history var name
I think is better if returns as
```
  return [
    value,
    set,
    history: historyRef.current,
    pointer: pointerRef.current,
    back,
    forward,
    go
  ]
 ```
 and then you can destructure as
 ```
 const [count, setCount, countHistory, countPointer, countBack, countForward, countGo ] =
    useStateWithHistory(1)
```

**Comment by WebDevSimplified** [comment]
Same as https://github.com/WebDevSimplified/useful-custom-react-hooks/issues/2#issuecomment-918094126
